FROM grafana/grafana:6.7.3
COPY ./dashboards /var/lib/grafana/dashboards
COPY ./provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY ./provisioning/datasources /etc/grafana/provisioning/datasources
