FROM grafana/grafana:11.4.0

COPY ./dashboards /var/lib/grafana/dashboards
COPY ./provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY ./provisioning/datasources /etc/grafana/provisioning/datasources
